### ISSUE TITLE
Fixing UrlTrackingInfo critical bug with Pre-release 9.4.1 results in templates being reverted to default, and non-default templates not showing correctly for all users.

### ISSUE THREAD

**Issue by mattmol** [DNNCommunity/DNN.Announcements#41]
## Software Versions
- DNN: 9.4.1

- Module: 7.2.1 has critical error https://github.com/DNNCommunity/DNN.Announcements/releases
9.4.1 Pre Release fixes critical error but the templates are loaded back to default, and new templates are only visible on authenticated users / admin accounts.  The default template is loaded for public viewing. https://github.com/SCullman/DNN.Announcements/releases/tag/09.04.01

## To Reproduce
1. Install DNN 9.4.1 on a site that has functioning announcements module 7.2.1.  Critical error will result. Described here https://github.com/DNNCommunity/DNN.Announcements/issues/38
Message:Invalid column name 'UrlTrackingInfo'.

2. If you upgrade the module with Announcements 9.4.1 pre release, the critical error is resolved, but the custom templates are lost... and re-customizing templates may not be visible to non-admin/non-authenticated users.

## Expected behavior

Have Announcements module load without critical errors or replacing templates, displaying templates correctly.

**Comment by valadas** [comment]
To be clear, the UrlTracking issue is PR #40 on this module. The fix is basically written but not yet merged into a release. The latest version of this module right now was tested up to 9.2.0

 @erikvb or @jncraig you guys think you have some time soon to publish a new release of this module?

**Comment by valadas** [comment]
The UrlTracking is solved and will be released in 7.2.2 shortly, for the templates issue, it looks like the source code that was taken from codeplex was outdated in relation to the release of the same version so I gonna assign this as an enhancement as it stands right now.

**Comment by Ceten** [comment]
Any new on this?
I just changed the template to remove the [PUBLISHDATE] but this only works in edit mode.
When not logged in the publish date is still shown.
Edit mode:
![image](https://user-images.githubusercontent.com/1673675/75955619-8bc19580-5eb6-11ea-849a-aec1b10944ef.png)
Outside of edit mode:
![image](https://user-images.githubusercontent.com/1673675/75955671-a1cf5600-5eb6-11ea-981e-c7259b8b1634.png)

**Comment by valadas** [comment]
>a few hours laters it seems that the template did update now.

cool, maybe it was a cache issue...
